version: "3.9"
services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && gunicorn smallissue.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: nginx
    volumes:
    - ./.config/nginx:/etc/nginx/conf.d
    - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
