# Generated by Django 3.2.7 on 2021-09-25 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(help_text='삭제 일시', null=True)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_leading', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
