# Generated by Django 3.2.7 on 2021-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20210928_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
