# Generated by Django 3.2.7 on 2021-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_alter_issue_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done')], default=0),
        ),
    ]
