# Generated by Django 3.2.7 on 2021-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
