# Generated by Django 3.2.7 on 2021-10-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_issue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
