# Generated by Django 3.2.7 on 2021-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_issue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
