# Generated by Django 3.2.7 on 2021-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_historicalissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='삭제 일시', null=True),
        ),
        migrations.AlterField(
            model_name='historicalissue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='삭제 일시', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='삭제 일시', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='삭제 일시', null=True),
        ),
    ]
