# Generated by Django 3.2.7 on 2021-10-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_auto_20211004_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalissuetagging',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='issuetagging',
            old_name='tags',
            new_name='tag',
        ),
    ]
