# Generated by Django 3.2.7 on 2021-10-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0015_issuehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuehistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
