# Generated by Django 3.2.7 on 2021-10-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0016_alter_issuehistory_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuehistory',
            options={'ordering': ['-history_date']},
        ),
        migrations.RenameField(
            model_name='issuehistory',
            old_name='created_at',
            new_name='history_date',
        ),
    ]
