# Generated by Django 3.2.7 on 2021-10-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0017_auto_20211005_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuehistory',
            old_name='object_id',
            new_name='issue_id',
        ),
    ]
