# Generated by Django 3.2.7 on 2021-10-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0019_auto_20211005_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuehistory',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='issue.issue'),
        ),
    ]
