# Generated by Django 3.2.7 on 2021-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0020_alter_issuehistory_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuehistory',
            name='issue',
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='issue_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
