# Generated by Django 3.2.7 on 2021-10-05 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0022_auto_20211005_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='subscribed_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
