# Generated by Django 3.2.7 on 2021-10-05 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0025_alter_issue_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='subscribers',
        )
        ,
        migrations.AddField(
            model_name='issue',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_issues', through='issue.IssueSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
