# Generated by Django 3.2.7 on 2021-10-09 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0027_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ManyToManyField(related_name='project_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
