# Generated by Django 3.2.7 on 2021-10-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0028_auto_20211009_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='user',
            new_name='users',
        ),
    ]
