# Generated by Django 3.2.7 on 2021-10-09 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0030_auto_20211009_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='Team',
        ),
    ]
