# Generated by Django 3.2.7 on 2021-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0031_rename_userrole_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='job_title',
            field=models.CharField(default='개발자', max_length=80),
            preserve_default=False,
        ),
    ]
