# Generated by Django 3.2.7 on 2021-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0035_alter_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalissue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (3, 'Hold')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (3, 'Hold')], default=0),
        ),
    ]
