# Generated by Django 3.2.8 on 2021-10-13 02:29

from django.db import migrations, models
import django.db.models.deletion
import issue.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issue', '0036_auto_20211011_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=issue.models.attachment_directory_path)),
                ('title', models.CharField(max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issue.project')),
            ],
        ),
    ]
