# Generated by Django 3.2.8 on 2021-10-13 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0037_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
            preserve_default=False,
        ),
    ]
