# Generated by Django 3.2.8 on 2021-10-13 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0038_attachment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='title',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
