# Generated by Django 3.2.7 on 2021-10-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='field',
            new_name='job',
        ),
    ]
