# Generated by Django 3.2.8 on 2021-10-13 02:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(upload_to=accounts.models.user_directory_path),
        ),
    ]
