name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate App Version
        id: appversion
        run: echo "::set-output name=version::app_$(TZ=Asia/Seoul date +'%y%m%d_%I%M%S')"

      - name: Change compose production yml name
        run: mv docker-compose.prod.yml docker-compose.yml

      - name: Generate deployment package
        run: zip -r ${{ steps.appversion.outputs.version }}.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: smallissue-backend
          environment_name: smallissue
          version_description: ${{ github.sha }} # TODO: commit 으로 변경
          version_label: ${{ steps.appversion.outputs.version }}
          region: ap-northeast-2
          deployment_package: ${{ steps.appversion.outputs.version }}.zip
